/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportLostRouteImport } from './routes/report.lost'
import { Route as ReportFoundRouteImport } from './routes/report.found'
import { Route as QrGenerateRouteImport } from './routes/qr.generate'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ItemsBrowseRouteImport } from './routes/items.browse'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLostItemsRouteImport } from './routes/dashboard.lost-items'
import { Route as DashboardFoundItemsRouteImport } from './routes/dashboard.found-items'
import { Route as DashboardClaimsRouteImport } from './routes/dashboard.claims'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLostRoute = ReportLostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => ReportRoute,
} as any)
const ReportFoundRoute = ReportFoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => ReportRoute,
} as any)
const QrGenerateRoute = QrGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => QrRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ItemsBrowseRoute = ItemsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLostItemsRoute = DashboardLostItemsRouteImport.update({
  id: '/lost-items',
  path: '/lost-items',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoundItemsRoute = DashboardFoundItemsRouteImport.update({
  id: '/found-items',
  path: '/found-items',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsRoute = DashboardClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/report': typeof ReportRouteWithChildren
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/found-items': typeof DashboardFoundItemsRoute
  '/dashboard/lost-items': typeof DashboardLostItemsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/browse': typeof ItemsBrowseRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/qr/generate': typeof QrGenerateRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/report': typeof ReportRouteWithChildren
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/found-items': typeof DashboardFoundItemsRoute
  '/dashboard/lost-items': typeof DashboardLostItemsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/browse': typeof ItemsBrowseRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/qr/generate': typeof QrGenerateRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/report': typeof ReportRouteWithChildren
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/found-items': typeof DashboardFoundItemsRoute
  '/dashboard/lost-items': typeof DashboardLostItemsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/browse': typeof ItemsBrowseRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/qr/generate': typeof QrGenerateRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/items'
    | '/profile'
    | '/qr'
    | '/report'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/items'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/claims'
    | '/dashboard/found-items'
    | '/dashboard/lost-items'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/items/$id'
    | '/items/browse'
    | '/profile/settings'
    | '/qr/generate'
    | '/report/found'
    | '/report/lost'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/items'
    | '/profile'
    | '/qr'
    | '/report'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/items'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/claims'
    | '/dashboard/found-items'
    | '/dashboard/lost-items'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/items/$id'
    | '/items/browse'
    | '/profile/settings'
    | '/qr/generate'
    | '/report/found'
    | '/report/lost'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/items'
    | '/profile'
    | '/qr'
    | '/report'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/items'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/claims'
    | '/dashboard/found-items'
    | '/dashboard/lost-items'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/items/$id'
    | '/items/browse'
    | '/profile/settings'
    | '/qr/generate'
    | '/report/found'
    | '/report/lost'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ItemsRoute: typeof ItemsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  QrRoute: typeof QrRouteWithChildren
  ReportRoute: typeof ReportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/lost': {
      id: '/report/lost'
      path: '/lost'
      fullPath: '/report/lost'
      preLoaderRoute: typeof ReportLostRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/found': {
      id: '/report/found'
      path: '/found'
      fullPath: '/report/found'
      preLoaderRoute: typeof ReportFoundRouteImport
      parentRoute: typeof ReportRoute
    }
    '/qr/generate': {
      id: '/qr/generate'
      path: '/generate'
      fullPath: '/qr/generate'
      preLoaderRoute: typeof QrGenerateRouteImport
      parentRoute: typeof QrRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/items/browse': {
      id: '/items/browse'
      path: '/browse'
      fullPath: '/items/browse'
      preLoaderRoute: typeof ItemsBrowseRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lost-items': {
      id: '/dashboard/lost-items'
      path: '/lost-items'
      fullPath: '/dashboard/lost-items'
      preLoaderRoute: typeof DashboardLostItemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/found-items': {
      id: '/dashboard/found-items'
      path: '/found-items'
      fullPath: '/dashboard/found-items'
      preLoaderRoute: typeof DashboardFoundItemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims': {
      id: '/dashboard/claims'
      path: '/claims'
      fullPath: '/dashboard/claims'
      preLoaderRoute: typeof DashboardClaimsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClaimsRoute: AdminClaimsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardClaimsRoute: typeof DashboardClaimsRoute
  DashboardFoundItemsRoute: typeof DashboardFoundItemsRoute
  DashboardLostItemsRoute: typeof DashboardLostItemsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClaimsRoute: DashboardClaimsRoute,
  DashboardFoundItemsRoute: DashboardFoundItemsRoute,
  DashboardLostItemsRoute: DashboardLostItemsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsBrowseRoute: typeof ItemsBrowseRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
  ItemsBrowseRoute: ItemsBrowseRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface ProfileRouteChildren {
  ProfileSettingsRoute: typeof ProfileSettingsRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSettingsRoute: ProfileSettingsRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface QrRouteChildren {
  QrGenerateRoute: typeof QrGenerateRoute
}

const QrRouteChildren: QrRouteChildren = {
  QrGenerateRoute: QrGenerateRoute,
}

const QrRouteWithChildren = QrRoute._addFileChildren(QrRouteChildren)

interface ReportRouteChildren {
  ReportFoundRoute: typeof ReportFoundRoute
  ReportLostRoute: typeof ReportLostRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportFoundRoute: ReportFoundRoute,
  ReportLostRoute: ReportLostRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ItemsRoute: ItemsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  QrRoute: QrRouteWithChildren,
  ReportRoute: ReportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
